---
title: "20230816_globBurdDisease"
output: pdf_document
date: "2023-08-16"
---

Data source: https://vizhub.healthdata.org/gbd-results/


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Modeling the global burden of infectious Diseases
 In the first version a location may have been covered by multiple 'regions'; here I use 
 "IHME-GBD_2019_DATA-afd4b08e-1.csv", in which only one classification of 21 mutually exclusive
 regions is used; The file only contains data on HIV, Tuberculosis and Zika virus; data are
 from male and female (but not "both"); ages are largely in 5 year intervals

Clean and load libraries
```{R}
rm(list=ls())
cat('\014')
graphics.off()

wd= getwd()

library('rjags')
library('tidyverse')
library('data.table')
library('gplots')
library('stringr')
library('reshape2')
library('ggpubr')
library('ggnewscale')
library('dtw')  #time series clustering
source('G:/My Drive/20230815_GlobBurdDisease/DBDA2E-utilities_mod.R')  #modified to fit markdown
```

## Data import
Obtain a file that contains all years only for "Tuberculosis","HIV/AIDS","Zika virus"
```{R}
allTime_HTZ_Deaths= read.csv('G:/My Drive/20230815_GlobBurdDisease/20230823_Deaths_HTZ_21reg_MF_5year/IHME-GBD_2019_DATA-afd4b08e-1.csv',stringsAsFactors = TRUE)   #HTZ= "Tuberculosis","HIV/AIDS","Zika virus"
#limit to metric== 'Percent' and remove 'Number'
allTime_HTZ_Deaths= allTime_HTZ_Deaths[allTime_HTZ_Deaths$metric=='Percent',]

allTime_HTZ_PrevInci= read.csv('G:/My Drive/20230815_GlobBurdDisease/20230907_PrevInci_HTZ_21reg_MF_5year/IHME-GBD_2019_DATA-cacc055a-1.csv',stringsAsFactors = TRUE)

allTime_HTZ= rbind.data.frame(allTime_HTZ_Deaths,allTime_HTZ_PrevInci)
```

Check data for completeness
```{R}
unique(allTime_HTZ$age) #this indicates entry "80-84" instead of "80-84 years" and two other such cases
levels(allTime_HTZ$age)[levels(allTime_HTZ$age)=='80-84']= '80-84 years'
levels(allTime_HTZ$age)[levels(allTime_HTZ$age)=='85-89']= '85-89 years'
levels(allTime_HTZ$age)[levels(allTime_HTZ$age)=='90-94']= '90-94 years'
levels(allTime_HTZ$age)

# Not all ages are in 5-year intervals -> remove the ones that are not
unique(allTime_HTZ$age[ str_detect(allTime_HTZ$age,'[0-9]+-[0-9]+ years')] ) #check
allTime_HTZ= allTime_HTZ[ str_detect(allTime_HTZ$age,'[0-9]+-[0-9]+ years'), ]

cause_location_tab= allTime_HTZ %>%
  filter(measure=='Deaths' & sex=='Male' & age=='30-34 years' ) %>%
  group_by(cause,location) %>%
  summarise(count= n_distinct(year))

dim(allTime_HTZ)
head(allTime_HTZ)
str(allTime_HTZ)

#all location - cause combinations should have 30 years
all(cause_location_tab$count == 30)
```

Encode 'cause' as number to allow indexing by it
```{R}
allTime_HTZ$disFac= as.numeric(as.factor(allTime_HTZ$cause))
dim(allTime_HTZ)
summary(allTime_HTZ$val)
summary(allTime_HTZ$year)
hist(allTime_HTZ$val[allTime_HTZ$measure=='Deaths'],main='Death percentages - all margins')
hist(allTime_HTZ$val[allTime_HTZ$measure=='Deaths'],xlim=c(0,0.1),breaks= 200,main='Zoom: Death percentages - all margins')
hist(allTime_HTZ$val[allTime_HTZ$measure=='Prevalence'],main='Prevalence percentages - all margins')
```
## Age- & sex- independent analysis
 Average percentages over all age groups for location-cause(disFac)-year combination
```{R}
allTime_HTZ_asi= data.frame( allTime_HTZ %>%   #asi= age-, sex- independent
  group_by(measure,location,cause,disFac,year) %>%
  summarize(val= mean(val),.groups='drop') )
head(allTime_HTZ_asi)
dim(allTime_HTZ_asi)
```
# Analysis of percentage of deaths
```{R}
allTime_HTZ_asi_D= allTime_HTZ_asi %>%
  filter(measure=='Deaths')
```

Visualize data
```{R}
ggplot(data=allTime_HTZ_asi_D,mapping=aes(x=year,y=val,group=location,color=location))+
  geom_point()+
  geom_line()+
  facet_wrap(~cause,scales='free_y')+
  guides(color='none')
```
First impression:
*HIV rises to about year 15, then steady decline; need to check if that is true for all countries
 or just impression from high-incidence ones
*some HIV outliers that need to be investigated
*In most countries, tuberculosis is steadily declining, but in some there appears to be outbreak
*Zika is only observed at high prevalence after about 25 years; huge variation between countries

Are there locations that did not have any case?
```{R}
allTime_HTZ_asi_D_sums= allTime_HTZ_asi_D %>%
  group_by(location,cause) %>%
  summarize(sumPerc= sum(val),.groups='drop')

allTime_HTZ_asi_D_sums[allTime_HTZ_asi_D_sums$sumPerc==0,]
```
15 locations did not have any case of Zika

Normalize to max percentages to get a clearer picture of dynamics in low incidence locations
```{R}
allTime_HTZ_asi_D_norm= allTime_HTZ_asi_D %>%
  group_by(location,cause,disFac) %>%
  mutate(val_maxNorm= val/ifelse(max(val)>0,max(val),1) ) %>%
  ungroup()

ggplot(data=allTime_HTZ_asi_D_norm,mapping=aes(x=year,y=val_maxNorm,group=location,color=location))+
  geom_point()+
  geom_line()+
  theme(axis.title.y= element_text('Normalized to highest incidence year'))+
  facet_wrap(~cause,scales='free_y')+
  guides(color='none')    
```

## Two-line model
Fit a two-line model that assumes a process leading to increase and later process
leading to decrease of death rate. See "20230905_twoLine_model.html/.Rmd" for
evaluation of the model.
Ignore Zika for now.
Identify the cause-location combinations that fit a decrease in death rate != 0
```{R}
source('G:/My Drive/20230815_GlobBurdDisease/20230905_twoLine_fit.R')

allTime_HT_asi= allTime_HTZ_asi[allTime_HTZ_asi$cause %in% c('HIV/AIDS','Tuberculosis'),]
#allTime_HT_asi_D= allTime_HT_asi[allTime_HT_asi$measure=='Deaths',]
groupedDF= allTime_HT_asi %>%
      group_by(location,cause,measure) %>%
      summarize(n(),.groups='drop') 
dim(groupedDF) #126 combinations
head(allTime_HT_asi)

if(! file.exists('G:/My Drive/20230815_GlobBurdDisease/20230908_MCMCcoefs.csv')){ #execute only if not yet done
  MCMCcoefs_DF= data.frame( matrix(NA,nrow=dim(groupedDF)[1],ncol=7))
  colnames(MCMCcoefs_DF)= c('location','cause','measure',
                            'b0_median','b1_median','b2_median','t_inflec_median')
  MCMCcoefs_DF$location <- factor(MCMCcoefs_DF$location, levels = levels(groupedDF$location))
  MCMCcoefs_DF$cause <- factor(MCMCcoefs_DF$cause, levels = levels(groupedDF$cause))
  MCMCcoefs_DF$measure <- factor(MCMCcoefs_DF$measure, levels = levels(groupedDF$measure))

  for(i in 1:dim(groupedDF)[1]){
    print(paste(i,'of',dim(groupedDF)[1]))
    currDF= allTime_HT_asi[allTime_HT_asi$location==groupedDF$location[i] & 
                          allTime_HT_asi$cause==groupedDF$cause[i] &
                          allTime_HT_asi$measure==groupedDF$measure[i]  ,]
    mcmcDF= twoLine_fit(t= currDF$year, y=currDF$val)
    
    HDIlower_b1= HDIofMCMC(mcmcDF$b1,credMass=.80)[1]  #lower bound of HDI -> greater than 0?
    HDIupper_b2= HDIofMCMC(mcmcDF$b2,credMass=.80)[2]  #upper bound of HDI -> lower than 0?
    # ! I use 80%, rather than 95% credibility intervals; while individual cases
     #may be incorrectly classified, overall trends should be correct; a high false-negative
     #rate needs to be avoided
    #Analysis could be extended by cases cross-informing each other (e.g. countries from same
     #region)
    
    MCMCcoefs_DF$location[i]= groupedDF$location[i]
    MCMCcoefs_DF$cause[i]= groupedDF$cause[i]
    MCMCcoefs_DF$measure[i]= groupedDF$measure[i]
    MCMCcoefs_DF$b0_median[i]= median(mcmcDF$b0)
    #only store rates if confidently different from 0
    MCMCcoefs_DF$b1_median[i]= ifelse(HDIlower_b1>0,median(mcmcDF$b1),NA) 
    MCMCcoefs_DF$b2_median[i]= ifelse(HDIupper_b2<0,median(mcmcDF$b2),NA)
    #only store inflection point if both rates confidently different from 0
    MCMCcoefs_DF$t_inflec_median[i]= 
      ifelse(HDIlower_b1>0 & HDIupper_b2<0,median(mcmcDF$t0),NA)
  }
  
  # write output so you do not need to run this code every time
  write.csv(MCMCcoefs_DF,
            'G:/My Drive/20230815_GlobBurdDisease/20230908_MCMCcoefs.csv',
            row.names = FALSE)
} else {
  MCMCcoefs_DF= read.csv('G:/My Drive/20230815_GlobBurdDisease/20230908_MCMCcoefs.csv',
                         stringsAsFactors=TRUE)
}
str(MCMCcoefs_DF)
dim(MCMCcoefs_DF)
```
34 of the 42 location-cause combinations exhibit a decrease (in some cases after
(initial increase) in death rate

```{R}
MCMCcoefs_DF$b0_median= as.numeric(MCMCcoefs_DF$b0_median)
MCMCcoefs_DF$b1_median= as.numeric(MCMCcoefs_DF$b1_median)
MCMCcoefs_DF$b2_median= as.numeric(MCMCcoefs_DF$b2_median)
MCMCcoefs_DF$t_inflec_median= as.numeric(MCMCcoefs_DF$t_inflec_median)
str(MCMCcoefs_DF)

ggplot(data=allTime_HT_asi[ allTime_HT_asi$cause=='HIV/AIDS',  ],
         mapping=aes(x=year,y=val,group=measure,color=measure))+
  geom_line()+
  ggtitle('HIV/AIDS')+
  guides(color="none")+
  facet_wrap(vars(location),ncol=7,scales='free_y')  #look at both fixed and free y

leg= ggpubr::get_legend(ggplot(data=allTime_HT_asi[ allTime_HT_asi$cause=='HIV/AIDS',  ],
                          mapping=aes(x=year,y=val,group=measure,color=measure))+
                          geom_line())

ggplot(data=allTime_HT_asi[ allTime_HT_asi$cause=='Tuberculosis',  ],
         mapping=aes(x=year,y=val,group=measure,color=measure))+
  geom_line()+
  ggtitle('Tuberculosis')+
  guides(color="none")+
  facet_wrap(vars(location),ncol=7)  #,scales='free_y' look at both fixed and free y

leg= ggpubr::get_legend(ggplot(data=allTime_HT_asi[ allTime_HT_asi$cause=='HIV/AIDS',  ],
                          mapping=aes(x=year,y=val,group=measure,color=measure))+
                          geom_line())
as_ggplot(leg)

```
Observations:
 
 HIV/AIDS:
 *in the countries with high death rates (Sub-Saharan Africa, Caribbean, Oceania), there is an
  inflection point ~2000-2005; from this point on, rates decrease in Sub-Saharan and Caribbean
  Africa regions and are stable in Oceania
 *the death rate is above prevalence in all regions -> this needs to be clarified: how can
  more people die from a disease than have the disease; how were prevalence data collected
 *the dynamics in lower death rate regions vary but most seem to have an inflection point
  within the 1990-2019 period; in regions with very low death rate, the death rate is still
  rising (e.g. Central Asia, Western Europe)
 *prevalence is generally rising or stable; incidences are close to 0 everywhere
 
 Tuberculosis:
  *the dynamics are quite different from HIV/AIDS
  *prevalence is higher than death rate in all regions
  *prevalence is generally declining or stable
  *death rate is generally declining from first recording on
  *there appears to be pos. correlation between prevalence and death rate, but with exceptions
   (e.g. countries with high prevalence and very low deaths) -> follow up on

-------
How meaningful are prevalence (and incidence) rates? Possible scenarios:
 *prevalence is tested in random sample; death rates should also be from
  random samples or all deaths recorded
 *all serious cases of the disease (the ones that may lead to death) are recorded
  ->probably true for countries with decent healthcare system
 *for each death it is determined if it was due to the cause of interest ->
  depends on environment (e.g. autopsies at unknown cause of death?) and disease
  manifestation (obvious signs of the disease?)
--------

## Summary of dynamics
Summarize the dynamics via coefficients b0 (level around 1990), b1 (increase rate),
b2 (decline rate) and t0 (inflection point)
[So far, I only plot entries with declining death rate, but it may be better to
 plot all and indicate value as missing if not confidently different from 0]
```{R}
MCMCcoefs_DF$loc_cause= paste(MCMCcoefs_DF$location,MCMCcoefs_DF$cause,sep=', ')
str(MCMCcoefs_DF)

#pivot:
MCMCcoefs_wide= pivot_wider(data=MCMCcoefs_DF,id_cols=c('loc_cause','location','cause'),
            names_from = c('measure'),
            values_from=c('b0_median','b1_median','b2_median','t_inflec_median'))

#manually sorted: 
MCMCcoefs_DF_NA= MCMCcoefs_wide[is.na(MCMCcoefs_wide$t_inflec_median_Deaths),] #no inflection point
MCMCcoefs_DF_noNA= MCMCcoefs_wide[!is.na(MCMCcoefs_wide$t_inflec_median_Deaths),] #with inflection point

#out of the data that do not have inflection year, get the ones that have decline
MCMCcoefs_DF_NA_decl= MCMCcoefs_DF_NA[!is.na(MCMCcoefs_DF_NA$b2_median_Deaths),]
MCMCcoefs_DF_NA_nodecl= MCMCcoefs_DF_NA[is.na(MCMCcoefs_DF_NA$b2_median_Deaths),]

#sort data with declining death rate (but no inflection) by decline of death rate
ord1= order(MCMCcoefs_DF_NA_decl$b2_median_Deaths)
#sort data with inflection by inflection year
ord2= order(MCMCcoefs_DF_noNA$t_inflec_median_Deaths) + max(ord1) #start after ord1
#sort data without declining death rate by increase in death rate
ord3= order(MCMCcoefs_DF_NA_nodecl$b1_median_Deaths) + max(ord2) #start after ord2

#order factor levels of 'loc_cause'
MCMCcoefs_patchw= rbind.data.frame(MCMCcoefs_DF_NA_decl,MCMCcoefs_DF_noNA,MCMCcoefs_DF_NA_nodecl)
ord= c(ord1,ord2,ord3)
MCMCcoefs_patchw$loc_cause= factor(MCMCcoefs_patchw$loc_cause,ordered=TRUE,
           levels= MCMCcoefs_patchw$loc_cause[ord])

DrD_melt= melt(MCMCcoefs_patchw,id.vars= c('loc_cause','location','cause'),
    measure.vars=
      c('b0_median_Deaths','b1_median_Deaths','b2_median_Deaths','t_inflec_median_Deaths',
        'b0_median_Prevalence','b1_median_Prevalence',
        'b2_median_Prevalence'  ))
 #drop Incidence (very low):'b0_median_Incidence', 'b1_median_Incidence','b2_median_Incidence','t_inflec_median_Incidence'
 #drop inflection of prevalence (very few observed): ,'t_inflec_median_Prevalence'
str(DrD_melt)

DrD_melt$coefType= rep('rate',dim(DrD_melt)[1])
DrD_melt$coefType[DrD_melt$variable %in% c('b0_median_Deaths',
                  'b0_median_Prevalence','b0_median_Incidence')]= 'basel.'
DrD_melt$coefType[DrD_melt$variable %in% c('t_inflec_median_Deaths',
                  't_inflec_median_Prevalence','t_inflec_median_Incidence')]= 'year'
head(DrD_melt)

ggplot()+
  geom_tile(data=DrD_melt[DrD_melt$coefType=='rate',],aes(x=variable,y=loc_cause,fill=value))+
  scale_fill_distiller(type = "seq", palette = "RdBu", guide = guide_colorbar(title.position = "top")) +
  ggnewscale::new_scale_fill() +
  #geom_tile(data=DrD_melt[DrD_melt$coefType=='basel.',],aes(x=variable,y=loc_cause,fill=value))+
  #scale_fill_distiller(type = "seq", palette = "Blues", guide=guide_colorbar(title.position = "top")) +
  #ggnewscale::new_scale_fill() +
  geom_tile(data=DrD_melt[DrD_melt$coefType=='year',],aes(x=variable,y=loc_cause,fill=value))+
  scale_fill_distiller(type = "div", palette = "Spectral", guide = guide_colorbar(title.position = "top")) +
  theme(axis.text.x=element_text(angle=90))+
  facet_grid(.~coefType, scales = "free_x", space = "free_x")


```

```{R}
allTime_HT_asi[allTime_HT_asi$location=='Eastern Sub-Saharan Africa' &
                             allTime_HT_asi$cause=='HIV/AIDS', ]
```

Work on one cause at a time; start with Tuberculosis
 most locations decrease steadily, but there seem to be 5 that increase, then decrease
Perform clustering at max-normalized data; worry later about differences in absolute percentages
```{R}
head(allTime_HTZ_asi_D_norm)

allTime_HIV_asi_norm= allTime_HTZ_asi_D_norm[allTime_HTZ_asi_D_norm$cause=='HIV/AIDS',]
HIV_wide= allTime_HIV_asi_norm %>%
  mutate(year= as.factor(year)) %>%
  select(location,year,val)%>%
  pivot_wider(names_from= year,values_from= val)

loc_labels= as.character(HIV_wide$location)
HIV_mtx= as.matrix(HIV_wide[,2:dim(HIV_wide)[2]])

#cluster timecourses
distMtx= dist(HIV_mtx,method='dtw')  #"dynamic time warping"
hc= hclust(distMtx,method='average')  #
plot(hc)  #,labels=loc_labels

#cut into three groups
dendroInd= cutree(hc,k=3)
allTime_HIV_asi_norm$dendGrp= dendroInd[match(allTime_HIV_asi_norm$location,loc_labels)]

ggplot(data=allTime_HIV_asi_norm[allTime_HIV_asi_norm$dendGrp ==1,], mapping=aes(x=year,y=val_maxNorm,color=location))+
  geom_point()+
  geom_line()+
  coord_cartesian(ylim=c(0,1))+
  theme(axis.title.y= element_text('Normalized to highest incidence year'))

ggplot(data=allTime_HIV_asi_norm[allTime_HIV_asi_norm$dendGrp %in% c(2,3),], mapping=aes(x=year,y=val_maxNorm,color=location))+
  geom_point()+
  geom_line()+
  coord_cartesian(ylim=c(0,1))+
  theme(axis.title.y= element_text('Normalized to highest incidence year'))

# ggplot(data=allTime_HIV_asi_norm[allTime_HIV_asi_norm$dendGrp==3,], mapping=aes(x=year,y=val_maxNorm,color=location))+
#   geom_point()+
#   geom_line()+
#   coord_cartesian(ylim=c(0,1))+
#   theme(axis.title.y= element_text('Normalized to highest incidence year'))
```
The normalized trajectories for the African locations + Caribbean are very similar

It is interesting to note that some trajectories have a clear turning point, from which on
 the death percentage decreases; this could be a simple point measure to compare trajectories and
 answer questions like:
 *Is turning point present for all countries in a region and does it occur simultaneously
 *Do different diseases have the a turning point at a similar time (i.e. is turning disease specific or
  due to change that affects several diseases)
 *Does the prevalence/infection rate decline with the disease rate (i.e. was there a reduction in the
  cause of the desease or did treatment get better?)

## Model1: 
Model percent of deaths as a linear function of time, where individual measurements
 (different locations, genders, ages) are distributed around the mean by a t-distribution;
 intercept has a uniform prior, slope normal prior with mean 0

Build model1:
 linear model of percentage vs year
  using t-distribution on slope
```{R}
allTime_HTZ$year= allTime_HTZ$year-1990  #Set 1990 as "year 0";

mod1Str='
model{
  for(i in 1:Ntotal){   #loop over all observations
    pc[i] ~ dt(b0[d[i]] + b1[d[i]]*year[i], sigma, nu )   #coefficients specific to disease
  }
  for(j in 1:Ndis){
    b0[j] ~ dunif(1/1000,1000)
    b1[j] ~ dnorm(0, 2^2)   #sd= 1/2
  }
  nuMin1 ~ dexp(1/29.0)
  nu= nuMin1 +1
  sigma~ dunif(0,1)
}'
```
MCMC for posteriors
```{R}
# data1List= list(
#   Ntotal= dim(data1)[1],
#   Ndis= length(unique(data1$cause)),
#   pc= data1$val,  #percentage
#   d= data1$disFac,
#   year= data1$year
# )

redData1List= list(
  Ntotal= dim(redData)[1],
  Ndis= length(unique(redData$cause)),
  pc= redData$val,  #percentage
  d= redData$disFac,
  year= redData$year
)

jags1= jags.model(file=textConnection(mod1Str),data=redData1List,n.chains=3)
```

```{R}
cS1= coda.samples(model=jags1,variable.names=c('b0','b1','sigma','nu'),n.iter=10000)
```

```{R}
for(i in 1:length(varnames(cS1))){
  diagMCMC(codaObject= cS1,parName=varnames(cS1)[i]  )
}
```
This does not produce good coefficient estimates. I probably need a different link function for data that are a percentage.