---
title: "20230816_globBurdDisease"
output: pdf_document
date: "2023-08-16"
---

Data source: https://vizhub.healthdata.org/gbd-results/

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Modeling the global burden of infectious Diseases

Clean and load libraries
```{R}
rm(list=ls())
cat('\014')
graphics.off()

setwd('H:/My Drive/20230815_GlobBurdDisease/20230815_infectiousDiseases')

library('rjags')
#source('H:/My Drive/learning/20230220_BayesianStatistics/20230504_BayesianDogsBook/DBDA2Eprogram #s/DBDA2E-utilities.R')
source('../DBDA2E-utilities_mod.R')  #modified to fit markdown
```

## Data import
Obtain a file that contains all years only for "Tuberculosis","HIV/AIDS","Zika virus",
 "All ages" and only "Male"
```{R}
### You only need to execute this once ######
# allTime_HTZ= data.frame()
# for(i in 1:19){
#   file_i= read.table(unz(
#     paste('IHME-GBD_2019_DATA-18eb38e3-',i,'.zip',sep=''),
#     paste('IHME-GBD_2019_DATA-18eb38e3-',i,'.csv',sep='')),
#   sep=',',header=TRUE)
#   
#   allTime_HTZ= rbind.data.frame(allTime_HTZ,
#     file_i[  file_i$age=='All ages' & 
#              file_i$sex=='Male' & 
#              file_i$cause %in% c("Tuberculosis","HIV/AIDS","Zika virus"),]
#   )
#   
#   rm('file_i')  #free memory
# }
# dim(allTime_HTZ)
# 
# write.csv(allTime_HTZ,"20230822_allTime_HTZ.csv")  #row.names=FALSE
```

```{R}
allTime_HTZ= read.csv('20230822_allTime_HTZ.csv',stringsAsFactors = TRUE)   #HTZ= "Tuberculosis","HIV/AIDS","Zika virus"
#limit to metric== 'Percent' and remove 'Number'
allTime_HTZ= allTime_HTZ[allTime_HTZ$metric=='Percent',]
```

Check data for completeness
```{R}
dim(allTime_HTZ)
head(allTime_HTZ)
str(allTime_HTZ)

cause_location_tab= allTime_HTZ %>%
  filter(measure=='Deaths' & sex=='Male' & age=='All ages' ) %>%
  group_by(cause,location) %>%
  summarise(count= n_distinct(year))

#all location - cause combinations should have 30 years
all(cause_location_tab$count == 30)
```
Set 1990 as "year 0";
Encode 'cause' as number to allow indexing by it
```{R}
allTime_HTZ$year= allTime_HTZ$year-1990
allTime_HTZ$disFac= as.numeric(as.factor(allTime_HTZ$cause))
dim(allTime_HTZ)
summary(allTime_HTZ$val)
summary(allTime_HTZ$year)
hist(allTime_HTZ$val,main='Disease percentages - all margins')
hist(allTime_HTZ$val,xlim=c(0,0.1),breaks= 200,main='Zoom: Disease percentages - all margins')
```
Regions appear according to different classifications: Commonwealth, World Bank, WHO, ...
```{R}
unique(allTime_HTZ$location)
```
Visualize data
```{R}
ggplot(data=allTime_HTZ,mapping=aes(x=year,y=val,group=location,color=location))+
  geom_point()+
  geom_line()+
  facet_wrap(~cause)+
  guides(color='none')
```

Are no cases of death by Zika virus reported?
```{R}
sum(allTime_HTZ$val[allTime_HTZ$cause=='Zika virus'])
allTime_HTZ[allTime_HTZ$cause=='Zika virus' & allTime_HTZ$val>0,]
length(allTime_HTZ$cause=='Zika virus' & allTime_HTZ$val>0)
```
 -> no, there are 4050 instances with at least one death; the precentages are
 just very low



*There seem to be lots of missing values (maybe due to incomplete import)
*More years would probably help to fit model
```{R}
HIV= redData[redData$cause=='HIV/AIDS',]
unique(redData$year)
HIV_tab= table(HIV$year,HIV$location)
apply(HIV_tab,2,sum)
```
Most have only one year; almost none has all 4

## Model1: 
Model percent of deaths as a linear function of time, where individual measurements
 (different locations, genders, ages) are distributed around the mean by a t-distribution;
 intercept has a uniform prior, slope normal prior with mean 0

Build model1:
 linear model of percentage vs year
  using t-distribution on slope
```{R}
mod1Str='
model{
  for(i in 1:Ntotal){   #loop over all observations
    pc[i] ~ dt(b0[d[i]] + b1[d[i]]*year[i], sigma, nu )   #coefficients specific to disease
  }
  for(j in 1:Ndis){
    b0[j] ~ dunif(1/1000,1000)
    b1[j] ~ dnorm(0, 2^2)   #sd= 1/2
  }
  nuMin1 ~ dexp(1/29.0)
  nu= nuMin1 +1
  sigma~ dunif(0,1)
}'
```
MCMC for posteriors
```{R}
# data1List= list(
#   Ntotal= dim(data1)[1],
#   Ndis= length(unique(data1$cause)),
#   pc= data1$val,  #percentage
#   d= data1$disFac,
#   year= data1$year
# )

redData1List= list(
  Ntotal= dim(redData)[1],
  Ndis= length(unique(redData$cause)),
  pc= redData$val,  #percentage
  d= redData$disFac,
  year= redData$year
)

jags1= jags.model(file=textConnection(mod1Str),data=redData1List,n.chains=3)
```

```{R}
cS1= coda.samples(model=jags1,variable.names=c('b0','b1','sigma','nu'),n.iter=10000)
```

```{R}
for(i in 1:length(varnames(cS1))){
  diagMCMC(codaObject= cS1,parName=varnames(cS1)[i]  )
}
```
This does not produce good coefficient estimates. I probably need a different link function for data that are a percentage.