---
title: "20230816_globBurdDisease"
output: pdf_document
date: "2023-08-16"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Modeling the global burden of infectious Diseases

Clean and load libraries
```{R}
rm(list=ls())
cat('\014')
graphics.off()

setwd('H:/My Drive/20230815_GlobBurdDisease/20230815_infectiousDiseases')

library('rjags')
#source('H:/My Drive/learning/20230220_BayesianStatistics/20230504_BayesianDogsBook/DBDA2Eprogram #s/DBDA2E-utilities.R')
source('../DBDA2E-utilities_mod.R')  #modified to fit markdown
```

## Model1: 
Model percent of deaths as a linear function of time, where individual measurements
 (different locations, genders, ages) are distributed around the mean by a t-distribution;
 intercept has a uniform prior, slope normal prior with mean 0

Data import
```{R}
file1= read.csv('./IHME-GBD_2019_DATA-18eb38e3-1/IHME-GBD_2019_DATA-18eb38e3-1.csv')
head(file1)  #contains 32 causes
unique(file1$year)
file2= read.csv('./IHME-GBD_2019_DATA-18eb38e3-2/IHME-GBD_2019_DATA-18eb38e3-2.csv')
head(file2)  #contains 32 causes
file10= read.csv('./IHME-GBD_2019_DATA-18eb38e3-10/IHME-GBD_2019_DATA-18eb38e3-10.csv')
head(file10)  #contains 32 causes
unique(file2$year)
colnames(file1)
sum(unique(file10$cause) %in% unique(file1$cause))/length(unique(file1$cause))
sum(unique(file10$location) %in% unique(file1$location))/length(unique(file1$location))
sum(unique(file10$year) %in% unique(file1$year))/length(unique(file1$year))
sum(unique(file10$age) %in% unique(file1$age))/length(unique(file1$age))
  #apparently year is what is incresing over files
```
Obtain a file that contains all years only for "Tuberculosis","HIV/AIDS","Zika virus",
 "All ages" and only "Male"
```{R}
### You only need to execute this once ######
# allTime_HTZ= data.frame()
# for(i in 1:19){
#   file_i= read.table(unz(
#     paste('IHME-GBD_2019_DATA-18eb38e3-',i,'.zip',sep=''),
#     paste('IHME-GBD_2019_DATA-18eb38e3-',i,'.csv',sep='')),
#   sep=',',header=TRUE)
#   
#   allTime_HTZ= rbind.data.frame(allTime_HTZ,
#     file_i[  file_i$age=='All ages' & 
#              file_i$sex=='Male' & 
#              file_i$cause %in% c("Tuberculosis","HIV/AIDS","Zika virus"),]
#   )
#   
#   rm('file_i')  #free memory
# }
# dim(allTime_HTZ)
# 
# write.csv(allTime_HTZ,"20230822_allTime_HTZ.csv")
```

```{R}
allTime_HTZ= read.csv('20230822_allTime_HTZ.csv')
```

```{R}
file1 %>%
  group_by(cause) %>%
  summarise(count= n_distinct(year))
```
Keep only metric "Percent"; 
Set 1990 as "year 0";
Encode 'cause' as factor
```{R}
data1= file1[file1$metric=='Percent',]
data1$year= data1$year-1990
data1$disFac= as.numeric(as.factor(data1$cause))
dim(data1)
summary(data1$val)
summary(data1$year)
```
Create a reduced dataset: only males, only 3 diseases, use only "All ages"
```{R}
redData= data1[data1$sex=='Male',]
redData= redData[redData$cause %in% c("Tuberculosis","HIV/AIDS","Zika virus"),]
redData$disFac= as.numeric(as.factor(redData$cause)) #need to ensure it starts at 1
#redData= redData[redData$location %in% c('East Asia','Central Europe','Southern Sub-Saharan  #Africa'),]
redData= redData[redData$age == 'All ages',]
dim(redData)
apply(redData,2,function(x){sum(is.na(x))})  #missing value check
```
Build model1:
 linear model of percentage vs year
  using t-distribution on slope
```{R}
mod1Str='
model{
  for(i in 1:Ntotal){   #loop over all observations
    pc[i] ~ dt(b0[d[i]] + b1[d[i]]*year[i], sigma, nu )   #coefficients specific to disease
  }
  for(j in 1:Ndis){
    b0[j] ~ dunif(1/1000,1000)
    b1[j] ~ dnorm(0, 2^2)   #sd= 1/2
  }
  nuMin1 ~ dexp(1/29.0)
  nu= nuMin1 +1
  sigma~ dunif(0,1)
}'
```
MCMC for posteriors
```{R}
# data1List= list(
#   Ntotal= dim(data1)[1],
#   Ndis= length(unique(data1$cause)),
#   pc= data1$val,  #percentage
#   d= data1$disFac,
#   year= data1$year
# )

redData1List= list(
  Ntotal= dim(redData)[1],
  Ndis= length(unique(redData$cause)),
  pc= redData$val,  #percentage
  d= redData$disFac,
  year= redData$year
)

jags1= jags.model(file=textConnection(mod1Str),data=redData1List,n.chains=3)
```

```{R}
cS1= coda.samples(model=jags1,variable.names=c('b0','b1','sigma','nu'),n.iter=10000)
```

```{R}
for(i in 1:length(varnames(cS1))){
  diagMCMC(codaObject= cS1,parName=varnames(cS1)[i]  )
}
```
This does not produce good coefficient estimates. I probably need a different link function for data that are a percentage.

Visualize data
```{R}
ggplot(data=redData,mapping=aes(x=year,y=val,group=location,color=location))+
  geom_point()+
  geom_line()+
  facet_wrap(~cause)+
  guides(color='none')
```
*There seem to be lots of missing values (maybe due to incomplete import)
*More years would probably help to fit model
```{R}
HIV= redData[redData$cause=='HIV/AIDS',]
unique(redData$year)
HIV_tab= table(HIV$year,HIV$location)
apply(HIV_tab,2,sum)
```
Most have only one year; almost none has all 4